[package]
name = "ddnnf_reasoning"
version = "0.4.0"
authors = []
edition = "2018"
license = "GNU LGPL-2.1"

[lib]
name = "ddnnf_lib"
path = "src/lib.rs"

[[bin]]
name = "ddnnife"
path = "src/bin/ddnnife.rs"

[[bin]]
name = "dhone"
path = "src/bin/dhone.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
lto = "fat" # enables link-time optimization
codegen-units = 1 # forbid parallel compiling
panic = "abort"
# for performance graphs: debug = true

[dependencies]
clap = "2.33.3"
rustyline = "9.0.0"
colour = "0.6.0"
mimalloc = { version = "*", default-features = false }
rug = "1.13.0"
nom = "6.1.2"
csv = "1.1"
workctl = "0.2.0" # parallelisation
file_diff = "1.0.0"
petgraph = "0.6.2"